function run_milestone1a_tests()
%RUN_MILESTONE1A_TESTS Run all Milestone 1A characterization tests.
rnfoundry.em.test.ensureLegacyWindingLayout();
tests = {@rnfoundry.em.test.test_rotary_machine, ...
         @rnfoundry.em.test.test_radial_slotted_factories, ...
         @rnfoundry.em.test.test_winding_completion, ...
         @rnfoundry.em.test.test_packing, ...
         @rnfoundry.em.test.test_serialization, ...
         @rnfoundry.em.test.test_validation};
for k = 1:numel(tests)
    feval(tests{k});
end
fprintf('Milestone 1A tests passed (%d groups).\n', numel(tests));
end
