function test_magnetic_sweep_options()
d=rnfoundry.em.test.baseInput('external',2);
m=rnfoundry.em.rotary.radial.SlottedPMMachine.fromRatios(d);
bad={{'SolveMethod','femmsession'},{'UseFemm',true},{'QuietFemm',true}, ...
     {'RotationMethod','SlidingMesh'}};
for k=1:numel(bad)
    o=struct(); o.(bad{k}{1})=bad{k}{2};
    rnfoundry.em.test.assertError(@() ...
        rnfoundry.em.rotary.radial.runRadialSlottedMagneticSweep(m,o), ...
        'rnfoundry:em:UnknownSweepOption');
end
rnfoundry.em.test.assertError(@() ...
    rnfoundry.em.rotary.radial.runRadialSlottedMagneticSweep(m,struct('NPositions',1)), ...
    'rnfoundry:em:InvalidSweepOptions');
end
