function state=classify_fea_test_availability(optedIn,classAvailable, ...
        sessionGatewayAvailable,postProcessorGatewayAvailable,runtimeLoadable)
%CLASSIFY_FEA_TEST_AVAILABILITY Pure decision logic for the real-FEA tier.
if ~optedIn
    state=struct('CanRun',false,'Kind','skipped', ...
        'Message',['FEA parity tests SKIPPED: set RNFOUNDRY_RUN_FEA_TESTS=1 ' ...
                   'in a configured xfemm/FEMM environment.']);
elseif ~classAvailable
    state=struct('CanRun',false,'Kind','unavailable-api', ...
        'Message','FEA parity tests UNAVAILABLE: xfemm.femmsession is not on the path.');
elseif ~(sessionGatewayAvailable&&postProcessorGatewayAvailable&&runtimeLoadable)
    state=struct('CanRun',false,'Kind','unavailable-runtime', ...
        'Message',['FEA parity tests UNAVAILABLE: required xfemm/FEMM native ' ...
                   'solver runtime is not available.']);
else
    state=struct('CanRun',true,'Kind','available', ...
        'Message','FEA parity environment available; running real parity tests.');
end
end
