function result=runLegacyRawMagneticSweep(machine,options)
%RUNLEGACYRAWMAGNETICSWEEP Established feasim femmsession oracle for tests.
if ~isfield(options,'DrawCoilInsulation'), options.DrawCoilInsulation=false; end
drawCoilInsulation=options.DrawCoilInsulation;
options=rmfield(options,'DrawCoilInsulation');
o=rnfoundry.em.rotary.radial.resolveMagneticSweepOptions(machine,options);
d=machine.toLegacyStruct(); d.MagFEASimMaterials.AirGap=o.AirGapMaterial;
d.FirstSlotCenter=0; d.MagFEASimPositions=linspace(0,1,o.NPositions);
simoptions=struct('DoBackIronCoreLoss',false,'MagFEASim',struct( ...
    'MagnetRegionMeshSize',o.MagnetRegionMeshSize, ...
    'BackIronRegionMeshSize',o.BackIronRegionMeshSize, ...
    'AirGapMeshSize',o.AirGapMeshSize,'OuterRegionsMeshSize',o.OuterRegionsMeshSize, ...
    'YokeRegionMeshSize',o.YokeRegionMeshSize,'CoilRegionMeshSize',o.CoilRegionMeshSize, ...
    'ShoeGapRegionMeshSize',o.ShoeGapRegionMeshSize));
np=max(1,ceil(d.pb/2)); n=o.NPositions; session=[];
for k=1:n
    extra={}; if k>1, extra={'FemmSession',session}; end
    [torque(k,1),~,~,tooth(k,1),flux,apos,aint,bpos,bint,d,session]= ...
        feasim_RADIAL_SLOTTED(d,simoptions,machine.thetap*d.MagFEASimPositions(k), ...
        'NPolePairs',np,'RotationMethod','SlidingMesh','SolveMethod','femmsession', ...
        'GatherIronLossData',false,'DrawCoilInsulation',drawCoilInsulation,'PhaseCurrents',zeros(machine.Armature.Winding.PhaseCount,1), ...
        extra{:}); %#ok<AGROW>
    direct(k,:)=flux; aPosition(k,:)=apos(:).'; bPosition(k,:)=bpos(:).'; %#ok<AGROW>
    aIntegral(k,:,:,:)=reshape(aint,[1,size(aint,1),size(aint,2),size(aint,3)]); %#ok<AGROW>
    bIntegral(k,:,:,:)=reshape(bint,[1,size(bint,1),size(bint,2),size(bint,3)]); %#ok<AGROW>
    airGap(k,:)=d.FluxDensityMagnitudeAirGap; %#ok<AGROW>
    if k==1
        labels=d.StatorDrawingInfo.CoilLabelLocations;
        coilAreas=zeros(d.CoilLayers,1);
        for layer=1:d.CoilLayers
            coilAreas(layer)=session.blockintegral(5,labels(layer,1),labels(layer,2));
        end
        coilArea=coilAreas(1);
        session.clearblock(); session.groupselectblock(d.FemmProblem.Groups.ArmatureBackIron);
        ironArea=session.blockintegral(5)/d.StatorDrawingInfo.NDrawnSlots*d.Qs;
        session.clearblock(); session.groupselectblock( ...
            [d.FemmProblem.Groups.Magnet,d.FemmProblem.Groups.RotorBackIron]);
        poleAngle=d.RotorDrawingInfo.NDrawnPoles*d.thetap/2;
        radialForce=dot([session.blockintegral(18),session.blockintegral(19)] ...
            /d.RotorDrawingInfo.NDrawnPoles,[cos(poleAngle),sin(poleAngle)]);
    end
end
delete(session);
result=struct('Positions',d.MagFEASimPositions(:),'PhysicalAngles', ...
    machine.thetap*d.MagFEASimPositions(:),'CoggingTorque',torque, ...
    'DirectFluxLinkage',direct,'ToothFluxDensity',tooth, ...
    'SlotVectorPotential',struct('Position',aPosition,'Integral',aIntegral), ...
    'SlotFlux',struct('Position',bPosition,'Integral',bIntegral), ...
    'AirGapField',struct('Magnitude',airGap),'CoilArea',coilArea,'CoilAreas',coilAreas, ...
    'DrawCoilInsulation',drawCoilInsulation,'ArmatureIronArea',ironArea,'PerPoleRadialForce',radialForce);
end
