function s = makeMagneticSweepData(n)
%MAKEMAGNETICSWEEPDATA Consistent raw-result constructor input.
if nargin < 1, n=3; end
s=struct('Positions',linspace(0,1,n).','CoggingTorque',zeros(n,1), ...
 'DirectFluxLinkage',zeros(n,3),'ToothFluxDensity',ones(n,1), ...
 'SlotVectorPotential',struct('Position',zeros(n,2),'Integral',zeros(n,2)), ...
 'SlotFlux',struct('Position',zeros(n,2),'Integral',zeros(n,2)), ...
 'AirGapField',struct('Theta',[0,1],'Magnitude',zeros(n,2)), ...
 'CoilArea',1,'ArmatureIronArea',2,'PerPoleRadialForce',3, ...
 'Provenance',struct('Solver','xfemm.femmsession'));
end
