function winding = makeResolvedWinding()
%MAKERESOLVEDWINDING Deterministic double-layer winding with no MEX dependency.
material = struct('Name','test copper','Resistivity',1.72e-8);
conductor = rnfoundry.em.winding.RoundWireConductor( ...
    material,2,0.5e-3,struct('Type','LegacyEnamelCorrelation'));
geometry = rnfoundry.em.winding.RadialSlottedCoilGeometry( ...
    2.5e-4,0.1,0.08,0.012,[0.1,0.1],0.2e-3);

layout = struct();
layout.Coils = reshape(mod(0:71,36)+1,12,6);
layout.Phases = repmat([1,-1],36,1);
s = struct('PhaseCount',3,'PoleCount',12,'LayerCount',2, ...
    'CoilCount',36,'BasicCoilCount',3,'BasicPoleCount',1, ...
    'BasicWindingRepetitions',12,'SlotCount',36,'BasicSlotCount',3, ...
    'CoilPitchSlots',3,'qcn',1,'qcd',1,'ypn',3,'ypd',1, ...
    'ParallelBranches',2,'Layout',layout,'TurnsPerCoil',20, ...
    'PackingFactor',0.7,'Conductor',conductor,'CoilGeometry',geometry);
winding = rnfoundry.em.winding.Winding(s);
end
