function length = rectCoilMTL(depth, height, thickness)
%RECTCOILMTL Modern namespace form of the legacy rectangular-coil kernel.
length = 2 .* (height + thickness) ...
       + 2 .* depth ...
       + 2 .* thickness ...
       + pi .* thickness;
end
